In [1]:
import scipy
import numpy as np
import cvxpy as cp
import matplotlib.pyplot as plt

from src.IterativeFitting import IterativeFitting as IF
from src.CorrFuncs import covariance_matrix, trend_est

In [2]:
x = np.array([2,6,11])
Nx = np.array([337,167,186,212])
M1x = 451
Lx = np.array([np.log(0.80),np.log(1.16),np.log(1.57)])
vx = np.array([0.0542,0.0563,0.0563])
A0 = M1x*Nx[1:]/(Nx.sum())

In [3]:
it_fit_ex = IF(Lx,A0,Nx,M1x)

In [4]:
A = it_fit_ex.convexProgram()

In [5]:
A

(array([ 70.33038633,  95.48567119, 124.67758726]),
 array([96.66961367, 90.51432881, 87.32241274]),
 160.50635522335585,
 176.49364477664415)

In [9]:
A_GL = it_fit_ex.GL()

In [10]:
A_GL

(array([ 70.20458464,  95.46963796, 124.85560373]),
 160.47017367350816,
 array([96.79541536, 90.53036204, 87.14439627]),
 176.52982632649184,
 2)

In [11]:
A_GLN = it_fit_ex.GL_linesearch()

In [12]:
A_GLN

(array([ 70.33753879,  95.44494158, 124.66704769]),
 160.55047193677308,
 array([96.66246121, 90.55505842, 87.33295231]),
 176.44952806322692,
 2)

In [13]:
trend_est(it_fit_ex,vx,x,cvx=True,unadj=True)

(0.045430215893878516,
 0.0004268215544488761,
 0.03343845236748605,
 0.0003493531472534518)