In [1]:
import scipy
import numpy as np
import cvxpy as cp
import matplotlib.pyplot as plt

from src.HamMethods import ham_vanilla, ham_solved
from src.CorrFuncs import trend_est, covariance_matrix

Initialize data

In [2]:
x = np.array([2,6,11])
Nx = np.array([337,167,186,212])
M1x = 451
Lx = np.array([np.log(0.80),np.log(1.16),np.log(1.57)])
vx = np.array([0.0542,0.0563,0.0563])
A0 = M1x*Nx[1:]/(Nx.sum())

In [3]:
a0 = 165
b0 = 172
B = np.array([93,96,90])

#### OR Example where everything works

In [4]:
A_fith, B_fith, a0_fith, b0_fith = ham_vanilla(b0,B,M1x,Lx,vx,a0)

In [5]:
b_hamh, v_hamh = trend_est(A_fith,B_fith,a0_fith,b0_fith,vx,x,Lx)

In [6]:
b_hamh

0.04588480137880012

In [7]:
v_hamh

0.000420818983411542

In [8]:
A_fits, B_fits, a0_fits, b0_fits = ham_solved(b0,B,M1x,Lx,vx,a0)

In [9]:
b_hams, v_hams = trend_est(A_fits,B_fits,a0_fits,b0_fits,vx,x,Lx)

In [10]:
b_hams

0.04588453176343965

In [11]:
v_hams

0.0004208194078717963

#### Another OR example where everything works (but it's hidden as RR)

In [9]:
x = np.array([9.06,27.,45.,64.8])
Nx = np.array([414,261,228,44,34])
A0 = np.array([61,69,22,19])
B = Nx[1:] - A0
a0 = 126
b0 = Nx[0] - a0
M1x = np.sum(A0) + a0
Lx = np.array([-0.2231435,-0.0001,0.5306283,0.8754687])
vx = np.array([0.2233380,0.2337519,0.3765137,0.4440046])
vx = vx**2
# Lx = np.log((A0*b0)/(a0*B))
# vx = 1/a0 - 1/b0 + 1/A0 - 1/B

In [10]:
A_fith, B_fith, a0_fith, b0_fith = ham_vanilla(b0,B,M1x,Lx,vx,a0)

In [11]:
A_fith

array([42.86671822, 39.59811018, 14.0486192 , 11.37901951])

In [12]:
B_fith

array([124.55384629,  92.05445382,  19.20930333,  11.02098809])

In [13]:
a0_fith

77.21190403475387

In [14]:
covariance_matrix(A_fith,B_fith,a0_fith,b0_fith,vx)

array([[0.04987986, 0.01852308, 0.01852308, 0.01852308],
       [0.01852308, 0.05463995, 0.01852308, 0.01852308],
       [0.01852308, 0.01852308, 0.14176257, 0.01852308],
       [0.01852308, 0.01852308, 0.01852308, 0.19714008]])

In [15]:
A_fits, B_fits, a0_fits, b0_fits = ham_solved(b0,B,M1x,Lx,vx,a0)

In [16]:
covariance_matrix(A_fits,B_fits,a0_fits,b0_fits,vx)

array([[0.04987986, 0.01852028, 0.01852028, 0.01852028],
       [0.01852028, 0.05463995, 0.01852028, 0.01852028],
       [0.01852028, 0.01852028, 0.14176257, 0.01852028],
       [0.01852028, 0.01852028, 0.01852028, 0.19714008]])

In [17]:
A_fits

array([42.86323567, 39.59541784, 14.04849145, 11.37902797])

In [21]:
a0_fits

77.2243631435358

In [22]:
B_fits

array([124.53969108,  92.04521175,  19.20850611,  11.02063911])

#### RR example where everything works

In [2]:
x = np.array([1.8286, 9.1992, 22.8571, 35.6667, 58.4257])
A = np.array([38, 43, 32, 16, 27])
a0 = 28
M1 = np.sum(A) + a0
B = np.array([43030.54, 53088.96, 45348.09, 19790.79, 19919.85])
b0 = 22185.73
L = np.array([-0.41673, -0.39555, -0.48842, -0.27903, 0.20232])
v = np.array([0.2510976, 0.2456013, 0.2633819, 0.3208115, 0.2861643])
v *= v

In [3]:
A_fith, B_fith, a0_fith, b0_fith = ham_vanilla(b0,B,M1,L,v,a0,OR=False)

In [4]:
A_fith

array([39.2398308 , 43.95115406, 31.43904148, 15.29204959, 22.53813069])

In [5]:
B_fith

array([49696.85380633, 54497.13802217, 42776.53841078, 16875.82902854,
       15369.85120717])

This matches! In other words, our vanilla Hamling copy matches what $\verb+dosresmeta+$ gives.

Next, we make sure our method also gives the same result

In [6]:
A_fits, B_fits, a0_fits, b0_fits = ham_solved(b0,B,M1,L,v,a0,OR=False)

In [7]:
A_fits

array([39.51239758, 44.2934568 , 31.61369796, 15.33310551, 22.62742335])

In [8]:
a0_fits

26.449454769982697